// Generated by CoffeeScript 1.4.0
(function() {
  var $;

  $ = jQuery;

  $.fn.tabs = function(options) {
    return this.each(function() {
      var thiz;
      thiz = $(this);
      thiz.find('nav li a').on('click', function(evt) {
        evt.preventDefault();
        thiz = $(this);
        thiz.closest('nav').find('a').removeClass('current');
        thiz.closest('nav').siblings('.content').children().hide();
        return $(thiz.addClass('current').attr('href')).show();
      });
      return $(thiz.find('nav li:first-child a').addClass('current').attr('href')).show();
    });
  };

}).call(this);
