// Generated by CoffeeScript 1.4.0
(function() {
  var path,
    __slice = [].slice;

  path = function() {
    var arg, args, _i, _len, _results;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = args.length; _i < _len; _i++) {
      arg = args[_i];
      _results.push(arg.replace('@', 'javascripts/lib/syntaxhighlighter/scripts/'));
    }
    return _results;
  };

  SyntaxHighlighter.autoloader.apply(null, path('html @shBrushXml.js', 'js @shBrushJScript.js'));

  SyntaxHighlighter.all();

}).call(this);
